import { Vendor, Question, Template, PastAnswerSet, FollowUpItem, Evidence } from './types';

export const INITIAL_VENDORS: Vendor[] = [
  { id: 'v1', name: 'A社', contactPerson: '山田 太郎', email: 'yamada@company-a.com' },
  { id: 'v2', name: 'B社', contactPerson: '鈴木 一郎', email: 'suzuki@company-b.com' },
  { id: 'v3', name: 'C社', contactPerson: '佐藤 花子', email: 'sato@company-c.com' },
];

export const QUESTIONS_SCS3: Question[] = [
  {
    id: 'scs3-01',
    text: 'セキュリティ責任者・担当部署・平時の連絡先リストを定めていますか。',
    guideline: 'SCS ★3 No.1',
    source: 'SCS',
    level: 'SCS3',
    controlId: '5.2',
    category: 'ガバナンス',
    evidenceExamples: ['体制図', '連絡先一覧', '責任者任命記録'],
    reviewCriteria: '責任者・担当部署・連絡先が明確で、最新化されているか確認する。',
    riskTags: ['体制', '連絡体制'],
    requiredFor: '中規模委託先推奨',
  },
  {
    id: 'scs3-02',
    text: '役員、従業員、社外要員に対する守秘義務を文書化し、説明していますか。',
    guideline: 'SCS ★3 No.2',
    source: 'SCS',
    level: 'SCS3',
    controlId: '6.6',
    category: '人的管理',
    evidenceExamples: ['誓約書', '就業規則', '委託契約書', '説明記録'],
    reviewCriteria: '守秘義務が文書化され、対象者に説明されているか確認する。',
    riskTags: ['守秘義務', '人的管理'],
    requiredFor: '中規模委託先推奨',
  },
  {
    id: 'scs3-03',
    text: 'セキュリティ対応方針を策定し、関係者に周知していますか。',
    guideline: 'SCS ★3 No.3',
    source: 'SCS',
    level: 'SCS3',
    controlId: '5.1',
    category: '方針・ルール',
    evidenceExamples: ['情報セキュリティ方針', '社内規程', '周知記録'],
    reviewCriteria: '方針が策定され、社内外の関係者に周知されているか確認する。',
    riskTags: ['方針', '規程'],
    requiredFor: '中規模委託先推奨',
  },
  {
    id: 'scs3-04',
    text: '年1回以上、体制・資産・ID・インシデント体制等を棚卸し、見直していますか。',
    guideline: 'SCS ★3 No.4',
    source: 'SCS',
    level: 'SCS3',
    controlId: '5.9',
    category: '定期見直し',
    evidenceExamples: ['棚卸記録', '見直し議事録', '改善記録'],
    reviewCriteria: '年1回以上の棚卸し・見直しが実施されているか確認する。',
    riskTags: ['棚卸', '継続的改善'],
    requiredFor: '中規模委託先推奨',
  },
  {
    id: 'scs3-05',
    text: '自社資産が接続している外部情報システムやクラウドサービスを一覧化していますか。',
    guideline: 'SCS ★3 No.5',
    source: 'SCS',
    level: 'SCS3',
    controlId: '5.23',
    category: '外部サービス管理',
    evidenceExamples: ['利用SaaS一覧', '外部接続一覧', 'クラウドサービス管理台帳'],
    reviewCriteria: '利用している外部サービスや接続先が一覧化されているか確認する。',
    riskTags: ['クラウド', '外部接続'],
    requiredFor: '中規模委託先推奨',
  },
  {
    id: 'scs3-06',
    text: '機密情報を共有する取引先と、機密情報の定義・取扱い・返還方法を明確にしていますか。',
    guideline: 'SCS ★3 No.6',
    source: 'SCS',
    level: 'SCS3',
    controlId: '5.19',
    category: '取引先管理',
    evidenceExamples: ['NDA', '契約書', '情報取扱い合意書'],
    reviewCriteria: '機密情報の範囲、取扱い、返還・削除方法が取引先と合意されているか確認する。',
    riskTags: ['機密情報', '契約', '取引先管理'],
    requiredFor: '中規模委託先推奨',
  },
  {
    id: 'scs3-07',
    text: 'ハードウェア、OS、ソフトウェアの一覧を作成し、管理ルールを定めていますか。',
    guideline: 'SCS ★3 No.7',
    source: 'SCS',
    level: 'SCS3',
    controlId: '5.9',
    category: '資産管理',
    evidenceExamples: ['資産台帳', 'ソフトウェア一覧', 'ライセンス管理表'],
    reviewCriteria: '管理対象資産が一覧化され、管理ルールが定められているか確認する。',
    riskTags: ['資産管理', 'ソフトウェア管理'],
    requiredFor: '中規模委託先推奨',
  },
  {
    id: 'scs3-08',
    text: 'ユーザIDの発行・変更・削除手続を定め、不要IDを速やかに無効化していますか。',
    guideline: 'SCS ★3 No.11',
    source: 'SCS',
    level: 'SCS3',
    controlId: '5.16',
    category: 'アクセス制御',
    evidenceExamples: ['ID管理台帳', '申請承認記録', '退職者ID削除記録'],
    reviewCriteria: 'IDライフサイクル管理が手順化され、不要IDが残存していないか確認する。',
    riskTags: ['ID管理', 'アクセス制御'],
    requiredFor: '中規模委託先推奨',
  },
  {
    id: 'scs3-09',
    text: '自社で取り扱うデータについて、バックアップ対象・頻度・復元手順を定めていますか。',
    guideline: 'SCS ★3 No.19',
    source: 'SCS',
    level: 'SCS3',
    controlId: '8.13',
    category: 'バックアップ',
    evidenceExamples: ['バックアップ設定', 'バックアップ手順書', 'リストア手順書'],
    reviewCriteria: 'バックアップ対象・頻度・復元手順が定義されているか確認する。',
    riskTags: ['バックアップ', '復旧'],
    requiredFor: '中規模委託先推奨',
  },
  {
    id: 'scs3-10',
    text: 'インシデント対応手順、連絡先、役割責任、報告フォーマットを文書化していますか。',
    guideline: 'SCS ★3 No.25',
    source: 'SCS',
    level: 'SCS3',
    controlId: '5.24',
    category: 'インシデント対応',
    evidenceExamples: ['インシデント対応手順書', '緊急連絡網', '報告様式'],
    reviewCriteria: 'インシデント発生時の対応手順・連絡先・役割が明確化されているか確認する。',
    riskTags: ['インシデント対応', '連絡体制'],
    requiredFor: '中規模委託先推奨',
  },
];

export const QUESTIONS_SCS4: Question[] = [
  {
    id: 'scs4-01',
    text: '関連法令、所管省庁・団体基準、取引先要求を把握し、社内ルールに反映していますか。',
    guideline: 'SCS ★4 No.1',
    source: 'SCS',
    level: 'SCS4',
    controlId: '5.31',
    category: 'ガバナンス',
    evidenceExamples: ['法令・要求事項一覧', '社内規程', 'ルール改訂記録'],
    reviewCriteria: '法令・業界基準・取引先要求を把握し、社内ルールへ反映しているか確認する。',
    riskTags: ['法令対応', '取引先要求'],
    requiredFor: '重要データ取扱委託先',
  },
  {
    id: 'scs4-02',
    text: 'セキュリティリスクについて経営判断できる会議体・委員会等を設置していますか。',
    guideline: 'SCS ★4 No.2',
    source: 'SCS',
    level: 'SCS4',
    controlId: '5.4',
    category: '経営関与',
    evidenceExamples: ['委員会規程', '会議体一覧', '議事録'],
    reviewCriteria: 'セキュリティリスクを経営層が判断する仕組みがあるか確認する。',
    riskTags: ['経営層', 'リスク管理'],
    requiredFor: '重要データ取扱委託先',
  },
  {
    id: 'scs4-03',
    text: 'サイバー攻撃や脆弱性情報を収集し、ログ等と組み合わせて予兆を分析できる体制がありますか。',
    guideline: 'SCS ★4 No.3',
    source: 'SCS',
    level: 'SCS4',
    controlId: '5.7',
    category: '脅威情報・監視',
    evidenceExamples: ['脅威情報収集手順', '監視運用記録', '脆弱性情報管理表'],
    reviewCriteria: '脅威情報や脆弱性情報を収集し、監視・分析に活用しているか確認する。',
    riskTags: ['脅威情報', '脆弱性', 'ログ監視'],
    requiredFor: '重要データ取扱委託先',
  },
  {
    id: 'scs4-04',
    text: '重要な機密情報を扱う取引先について、年1回以上セキュリティ対策状況を把握していますか。',
    guideline: 'SCS ★4 No.10',
    source: 'SCS',
    level: 'SCS4',
    controlId: '5.22',
    category: '取引先管理',
    evidenceExamples: ['取引先評価記録', 'チェックシート', '評価結果一覧'],
    reviewCriteria: '重要な機密情報を扱う取引先の対策状況を定期的に確認しているか確認する。',
    riskTags: ['取引先管理', '機密情報', '定期確認'],
    requiredFor: '重要データ取扱委託先',
  },
  {
    id: 'scs4-05',
    text: '取引先との間で、インシデント発生時の通知義務、連絡先、再発防止協議方法を明確にしていますか。',
    guideline: 'SCS ★4 No.11',
    source: 'SCS',
    level: 'SCS4',
    controlId: '5.24',
    category: 'インシデント連携',
    evidenceExamples: ['契約書', 'インシデント連絡体制', '通知義務条項'],
    reviewCriteria: 'インシデント発生時の通知・連絡・再発防止協議の方法が合意されているか確認する。',
    riskTags: ['インシデント対応', '取引先管理', '契約'],
    requiredFor: '重要データ取扱委託先',
  },
  {
    id: 'scs4-06',
    text: '契約終了時に、機密情報・アクセス権を回収または破棄するチェック手順がありますか。',
    guideline: 'SCS ★4 No.12',
    source: 'SCS',
    level: 'SCS4',
    controlId: '5.11',
    category: '契約終了管理',
    evidenceExamples: ['契約終了チェックシート', '削除証明', 'アクセス権削除記録'],
    reviewCriteria: '契約終了時の情報返却・削除・アクセス権削除が手順化されているか確認する。',
    riskTags: ['契約終了', 'データ削除', 'アクセス権'],
    requiredFor: '重要データ取扱委託先',
  },
  {
    id: 'scs4-07',
    text: '重要情報を扱うシステムのアクセス権について、付与条件・設定手順・定期確認を定めていますか。',
    guideline: 'SCS ★4 No.24',
    source: 'SCS',
    level: 'SCS4',
    controlId: '5.18',
    category: 'アクセス制御',
    evidenceExamples: ['アクセス権台帳', '権限付与基準', '棚卸記録'],
    reviewCriteria: '重要システムのアクセス権が最小権限で管理され、定期確認されているか確認する。',
    riskTags: ['アクセス制御', '重要システム', '最小権限'],
    requiredFor: '重要データ取扱委託先',
  },
  {
    id: 'scs4-08',
    text: '社外持出し端末・記憶媒体、重要システムのデータベースを暗号化していますか。',
    guideline: 'SCS ★4 No.29',
    source: 'SCS',
    level: 'SCS4',
    controlId: '8.24',
    category: '暗号化',
    evidenceExamples: ['暗号化設定', '端末管理台帳', 'データベース暗号化設定'],
    reviewCriteria: '重要情報が保存される端末・媒体・データベースが暗号化されているか確認する。',
    riskTags: ['暗号化', '端末管理', '重要情報'],
    requiredFor: '重要データ取扱委託先',
  },
  {
    id: 'scs4-09',
    text: 'ファイアウォール、プロキシ、認証サーバ等のログを取得・保管し、定期的に確認していますか。',
    guideline: 'SCS ★4 No.35',
    source: 'SCS',
    level: 'SCS4',
    controlId: '8.15',
    category: 'ログ管理',
    evidenceExamples: ['ログ保管設定', 'ログレビュー記録', '監視設定'],
    reviewCriteria: '重要なログを取得・保管し、定期的に確認しているか確認する。',
    riskTags: ['ログ管理', '監視', '検知'],
    requiredFor: '重要データ取扱委託先',
  },
  {
    id: 'scs4-10',
    text: '重要システムについて、復旧目標に合うバックアップと復元確認を実施していますか。',
    guideline: 'SCS ★4 No.32 / No.44',
    source: 'SCS',
    level: 'SCS4',
    controlId: '8.13',
    category: 'バックアップ・復旧',
    evidenceExamples: ['バックアップ設計', '復元テスト記録', 'BCP関連資料'],
    reviewCriteria: '重要システムの復旧目標に対して、バックアップと復元確認が実施されているか確認する。',
    riskTags: ['バックアップ', '復旧', 'BCP'],
    requiredFor: '重要データ取扱委託先',
  },
];

export const QUESTIONS_CIS: Question[] = [
  {
    id: 'cis-01',
    text: '企業資産、端末、サーバ、クラウド資産を一覧化し、未管理資産を把握していますか。',
    guideline: 'CIS Control 1',
    source: 'CIS',
    level: 'CIS',
    controlId: '5.9',
    category: '資産管理',
    evidenceExamples: ['資産台帳', 'クラウド資産一覧', '端末管理台帳'],
    reviewCriteria: '企業資産が一覧化され、未管理資産を把握できる状態か確認する。',
    riskTags: ['資産管理', 'クラウド'],
    requiredFor: 'CIS Controls',
  },
  {
    id: 'cis-02',
    text: '重要データを識別・分類し、保管・利用・廃棄ルールを定めていますか。',
    guideline: 'CIS Control 3',
    source: 'CIS',
    level: 'CIS',
    controlId: '5.12',
    category: 'データ保護',
    evidenceExamples: ['情報分類表', 'データ取扱規程', 'データ廃棄手順'],
    reviewCriteria: '重要データの分類とライフサイクル管理が定義されているか確認する。',
    riskTags: ['データ保護', '情報分類'],
    requiredFor: 'CIS Controls',
  },
  {
    id: 'cis-03',
    text: '利用者ID、管理者ID、サービスアカウントを適切に管理していますか。',
    guideline: 'CIS Control 5',
    source: 'CIS',
    level: 'CIS',
    controlId: '5.16',
    category: 'アカウント管理',
    evidenceExamples: ['アカウント一覧', '棚卸記録', '管理者ID一覧'],
    reviewCriteria: '利用者ID・管理者ID・サービスアカウントが一覧化され、棚卸されているか確認する。',
    riskTags: ['ID管理', '管理者権限'],
    requiredFor: 'CIS Controls',
  },
  {
    id: 'cis-04',
    text: '必要最小限の権限付与、権限変更、権限削除の手順を運用していますか。',
    guideline: 'CIS Control 6',
    source: 'CIS',
    level: 'CIS',
    controlId: '5.18',
    category: 'アクセス制御',
    evidenceExamples: ['アクセス権申請', '承認履歴', '権限棚卸記録'],
    reviewCriteria: 'アクセス権が最小権限で付与され、変更・削除手順が運用されているか確認する。',
    riskTags: ['アクセス制御', '最小権限'],
    requiredFor: 'CIS Controls',
  },
  {
    id: 'cis-05',
    text: '脆弱性を継続的に把握し、優先順位を付けて修正していますか。',
    guideline: 'CIS Control 7',
    source: 'CIS',
    level: 'CIS',
    controlId: '8.8',
    category: '脆弱性管理',
    evidenceExamples: ['脆弱性診断結果', 'パッチ適用記録', '修正計画'],
    reviewCriteria: '脆弱性を継続的に把握し、リスクに応じて修正しているか確認する。',
    riskTags: ['脆弱性', 'パッチ管理'],
    requiredFor: 'CIS Controls',
  },
  {
    id: 'cis-06',
    text: '監査ログを取得・保管し、攻撃検知や調査に利用できる状態にしていますか。',
    guideline: 'CIS Control 8',
    source: 'CIS',
    level: 'CIS',
    controlId: '8.15',
    category: 'ログ管理',
    evidenceExamples: ['ログ設定', 'ログ保管ポリシー', 'ログレビュー記録'],
    reviewCriteria: '監査ログが取得・保管され、調査に利用できる状態か確認する。',
    riskTags: ['ログ管理', '検知'],
    requiredFor: 'CIS Controls',
  },
  {
    id: 'cis-07',
    text: 'マルウェア対策を導入し、検知・隔離・更新を継続的に実施していますか。',
    guideline: 'CIS Control 10',
    source: 'CIS',
    level: 'CIS',
    controlId: '8.7',
    category: 'マルウェア対策',
    evidenceExamples: ['EDR設定', 'ウイルス対策ソフト設定', '検知レポート'],
    reviewCriteria: 'マルウェア対策が導入され、検知・隔離・更新が継続されているか確認する。',
    riskTags: ['マルウェア', 'EDR'],
    requiredFor: 'CIS Controls',
  },
  {
    id: 'cis-08',
    text: 'データ復旧手順を定め、バックアップから復元できることを確認していますか。',
    guideline: 'CIS Control 11',
    source: 'CIS',
    level: 'CIS',
    controlId: '8.13',
    category: 'バックアップ・復旧',
    evidenceExamples: ['バックアップ設定', '復元テスト記録', '復旧手順書'],
    reviewCriteria: 'バックアップ取得だけでなく、復元確認まで実施しているか確認する。',
    riskTags: ['バックアップ', '復旧'],
    requiredFor: 'CIS Controls',
  },
  {
    id: 'cis-09',
    text: '自社が利用するサービス提供者・委託先を評価し、適切に管理していますか。',
    guideline: 'CIS Control 15',
    source: 'CIS',
    level: 'CIS',
    controlId: '5.19',
    category: 'サービスプロバイダ管理',
    evidenceExamples: ['委託先評価表', '契約管理台帳', 'サービス提供者一覧'],
    reviewCriteria: '委託先・サービス提供者の評価、契約、継続管理が実施されているか確認する。',
    riskTags: ['委託先管理', 'サプライチェーン'],
    requiredFor: 'CIS Controls',
  },
  {
    id: 'cis-10',
    text: 'インシデント対応方針、役割、手順、連絡体制を整備していますか。',
    guideline: 'CIS Control 17',
    source: 'CIS',
    level: 'CIS',
    controlId: '5.24',
    category: 'インシデント対応',
    evidenceExamples: ['IR手順書', '訓練記録', '緊急連絡網'],
    reviewCriteria: 'インシデント対応方針・役割・手順・連絡体制が文書化されているか確認する。',
    riskTags: ['インシデント対応', '訓練'],
    requiredFor: 'CIS Controls',
  },
];

/** 全設問カタログ（導出エンジンの既定入力・controlId 突合の基礎）。 */
export const ALL_QUESTIONS: Question[] = [
  ...QUESTIONS_SCS3,
  ...QUESTIONS_SCS4,
  ...QUESTIONS_CIS,
];

export const INITIAL_TEMPLATES: Template[] = [
  { id: 't1', name: 'SCS ⭐︎3（中規模委託先推奨）', questions: QUESTIONS_SCS3 },
  { id: 't2', name: 'SCS ⭐︎4（重要データ取扱委託先）', questions: QUESTIONS_SCS4 },
  { id: 't3', name: 'CIS Controls', questions: QUESTIONS_CIS },
];

export const INITIAL_PAST_ANSWERS: PastAnswerSet[] = [
  {
    id: 'pa1',
    name: 'SCS ⭐︎3（2025年回答：S社向け）',
    templateId: 't1',
    year: '2025年',
    target: 'S社向け',
    answers: {
      'scs3-01': 'セキュリティ責任者、情報システム部、平時・緊急時の連絡先を一覧化し、四半期ごとに更新しています。',
      'scs3-02': '役員・従業員・派遣社員を対象に守秘義務誓約書を取得し、入社時研修で説明しています。',
      'scs3-03': '情報セキュリティ基本方針を2024年4月に制定し、社内ポータルと委託先向け資料で周知しています。',
      'scs3-04': '年1回、資産台帳、ID一覧、インシデント対応体制を棚卸し、改善事項を管理表で追跡しています。',
      'scs3-05': '利用SaaS、外部接続先、クラウドサービスを管理台帳に記録し、追加・廃止時に更新しています。',
    },
  },
];

/**
 * 証跡レジストリの初期データ。controlId を軸に登録し、様式（テンプレート）が違っても
 * 同一管理策IDの回答で再利用候補として提示できるようにする。
 */
export const INITIAL_EVIDENCES: Evidence[] = [
  {
    id: 'ev1',
    fileName: 'security_policy_and_awareness_record.pdf',
    controlId: '5.1',
    registeredAt: '2025-04-01',
    validUntil: '2026-03-31',
    version: '2024.4',
    disclosureLevel: '提出可',
  },
  {
    id: 'ev2',
    fileName: 'id_lifecycle_approval_records.xlsx',
    controlId: '5.16',
    registeredAt: '2025-06-15',
    validUntil: '2026-06-14',
    version: '1.2',
    disclosureLevel: 'マスキング要',
  },
  {
    id: 'ev3',
    fileName: 'backup_restore_procedure_and_test_log.pdf',
    controlId: '8.13',
    registeredAt: '2025-05-20',
    validUntil: '2026-05-19',
    version: '3.0',
    disclosureLevel: '閲覧のみ',
  },
];

export const INITIAL_FOLLOWUPS: FollowUpItem[] = [
  {
    id: 'f1',
    title: 'セキュリティポリシの役員承認フローの整備',
    agreement: '現状のセキュリティポリシーは部長決裁となっているため、次回改訂時に役員（取締役会）の承認フローを正式整備し、承認書コピーを提出すること。',
    deadline: '2026-08-31',
    status: '検討中',
    assignee: '情シス：佐藤',
  },
];
